# Railway Deployment
services:
  n8n:
    image: n8nio/n8n:latest
    restart: always
    ports:
      - "5678:5678"
    environment:
      - N8N_HOST=${{RAILWAY_PUBLIC_DOMAIN}}
      - N8N_PORT=5678
      - N8N_PROTOCOL=https
      - NODE_ENV=production
      - WEBHOOK_URL=https://${{RAILWAY_PUBLIC_DOMAIN}}/
      - GENERIC_TIMEZONE=America/New_York
      - N8N_LOG_LEVEL=info
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=secure-news-bot-2024
      - N8N_ENCRYPTION_KEY=n8n-news-automation-encryption-key-32
    volumes:
      - n8n_data:/home/node/.n8n

volumes:
  n8n_data: