services:
  - type: web
    name: n8n-automation
    env: docker
    dockerfilePath: ./Dockerfile
    port: 5678
    envVars:
      - key: N8N_HOST
        value: "0.0.0.0"
      - key: N8N_PROTOCOL  
        value: "http"
      - key: N8N_BASIC_AUTH_ACTIVE
        value: "false"
      - key: GENERIC_TIMEZONE
        value: "UTC"
      - key: N8N_LOG_LEVEL
        value: "info"